from django.urls import path
from .views import (
    RegisterPatientView,
    PatientMeView,
    EnterQueueView,
    PatientQueueStatusView,
    PatientDocumentsView,
    patient_dashboard,
    DoctorQueueView,
    DoctorConsultationDetailView,
    DoctorConsultationUpdateView,
    doctor_start_consultation,
    doctor_finish_consultation,
    doctor_generate_document,
    profile,
    twilio_token,
    PatientUpdateView,
    DocumentDownloadView,
    video_exit,
    generate_video_token,
    send_document_whatsapp,
)

urlpatterns = [
    path("register/patient/", RegisterPatientView.as_view(), name="register_patient"),
    path("patient/me/", PatientMeView.as_view(), name="patient_me"),
    path("patient/me/update/", PatientUpdateView.as_view(), name="patient_update"),
    path("patient/dashboard/", patient_dashboard, name="patient_dashboard"),
    path("patient/queue/", EnterQueueView.as_view(), name="enter_queue"),
    path("patient/queue/status/", PatientQueueStatusView.as_view(), name="patient_queue_status"),
    path("patient/documents/", PatientDocumentsView.as_view(), name="patient_documents"),
    path("documents/<int:pk>/download/", DocumentDownloadView.as_view(), name="document_download"),
    path("doctor/queue/", DoctorQueueView.as_view(), name="doctor_queue"),
    path("doctor/consultations/<int:pk>/", DoctorConsultationDetailView.as_view(), name="doctor_consultation"),
    path("doctor/consultations/<int:pk>/update/", DoctorConsultationUpdateView.as_view(), name="doctor_consultation_update"),
    path("doctor/queue/<int:queue_id>/start/", doctor_start_consultation, name="doctor_start_consultation"),
    path("doctor/consultations/<int:consultation_id>/finish/", doctor_finish_consultation, name="doctor_finish_consultation"),
    path("doctor/consultations/<int:consultation_id>/document/", doctor_generate_document, name="doctor_generate_document"),
    path("doctor/consultations/<int:consultation_id>/twilio-token/", twilio_token, name="twilio_token"),
    path("doctor/consultations/<int:consultation_id>/video-exit/", video_exit, name="video_exit"),
    path("video/token/", generate_video_token, name="generate_video_token"),
    path("documents/send-whatsapp/", send_document_whatsapp, name="send_document_whatsapp"),
    path("profile/", profile, name="profile"),
]
